//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bao_cao
    {
        public int ma_bao_cao { get; set; }
        public string ma_code_bao_cao { get; set; }
        public string ten_bao_cao { get; set; }
        public string loai_bao_cao { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string tom_tat_bo_loc { get; set; }
        public string duong_dan_file { get; set; }
        public string noi_dung_bao_cao_json { get; set; }
        public string ghi_chu { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
