//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_chuyen_giao
    {
        public int ma_chuyen { get; set; }
        public int ma_don_hang { get; set; }
        public string trang_thai_giao { get; set; }
        public string ghi_chu_giao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        public virtual chuyen_giao_hang chuyen_giao_hang { get; set; }
        public virtual don_hang don_hang { get; set; }
    }
}
