//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_phieu_nhap_kho
    {
        public int ma_chi_tiet_phieu_nhap { get; set; }
        public int ma_phieu_nhap { get; set; }
        public int ma_sku { get; set; }
        public int so_luong_ke_hoach { get; set; }
        public int so_luong_thuc_nhan { get; set; }
        public Nullable<decimal> don_gia_nhap { get; set; }
        public Nullable<decimal> thanh_tien { get; set; }
    
        public virtual phieu_nhap_kho phieu_nhap_kho { get; set; }
        public virtual san_pham_sku san_pham_sku { get; set; }
    }
}
