//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_hang
    {
        public int ma_chi_tiet_don { get; set; }
        public int ma_don_hang { get; set; }
        public int ma_sku { get; set; }
        public int so_luong { get; set; }
        public decimal don_gia { get; set; }
        public decimal gia_von { get; set; }
        public decimal thanh_tien_dong { get; set; }
    
        public virtual don_hang don_hang { get; set; }
        public virtual san_pham_sku san_pham_sku { get; set; }
    }
}
