//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_kiem_ke
    {
        public int ma_chi_tiet_kiem_ke { get; set; }
        public int ma_phieu_kiem_ke { get; set; }
        public int ma_sku { get; set; }
        public int so_luong_he_thong { get; set; }
        public int so_luong_thuc_te { get; set; }
        public Nullable<int> chenh_lech { get; set; }
    
        public virtual phieu_kiem_ke phieu_kiem_ke { get; set; }
        public virtual san_pham_sku san_pham_sku { get; set; }
    }
}
