//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyen_giao_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chuyen_giao_hang()
        {
            this.chi_tiet_chuyen_giao = new HashSet<chi_tiet_chuyen_giao>();
        }
    
        public int ma_chuyen { get; set; }
        public string ma_code_chuyen { get; set; }
        public int ma_tai_xe { get; set; }
        public Nullable<System.DateTime> ngay_khoi_hanh { get; set; }
        public Nullable<System.DateTime> ngay_hoan_tat { get; set; }
        public string trang_thai { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_chuyen_giao> chi_tiet_chuyen_giao { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
