//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DO_AN_QLKEntities : DbContext
    {
        public DO_AN_QLKEntities()
            : base("name=DO_AN_QLKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bao_cao> bao_cao { get; set; }
        public virtual DbSet<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual DbSet<chi_tiet_kiem_ke> chi_tiet_kiem_ke { get; set; }
        public virtual DbSet<chi_tiet_phieu_nhap_kho> chi_tiet_phieu_nhap_kho { get; set; }
        public virtual DbSet<danh_muc> danh_muc { get; set; }
        public virtual DbSet<don_hang> don_hang { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<khu_vuc_kho> khu_vuc_kho { get; set; }
        public virtual DbSet<khuyen_mai> khuyen_mai { get; set; }
        public virtual DbSet<lo_hang> lo_hang { get; set; }
        public virtual DbSet<mau_san_pham> mau_san_pham { get; set; }
        public virtual DbSet<nguoi_dung> nguoi_dung { get; set; }
        public virtual DbSet<nha_cung_cap> nha_cung_cap { get; set; }
        public virtual DbSet<phieu_kiem_ke> phieu_kiem_ke { get; set; }
        public virtual DbSet<phieu_nhap_kho> phieu_nhap_kho { get; set; }
        public virtual DbSet<san_pham_sku> san_pham_sku { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<thuoc_tinh> thuoc_tinh { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_ApDungKhuyenMai_Result> sp_ApDungKhuyenMai(Nullable<int> ma_don_hang, string ma_code_khuyen_mai)
        {
            var ma_don_hangParameter = ma_don_hang.HasValue ?
                new ObjectParameter("ma_don_hang", ma_don_hang) :
                new ObjectParameter("ma_don_hang", typeof(int));
    
            var ma_code_khuyen_maiParameter = ma_code_khuyen_mai != null ?
                new ObjectParameter("ma_code_khuyen_mai", ma_code_khuyen_mai) :
                new ObjectParameter("ma_code_khuyen_mai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApDungKhuyenMai_Result>("sp_ApDungKhuyenMai", ma_don_hangParameter, ma_code_khuyen_maiParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoDoanhThuTheoThoiGian_Result> sp_BaoCaoDoanhThuTheoThoiGian(Nullable<System.DateTime> tu_ngay, Nullable<System.DateTime> den_ngay, string nhom_theo)
        {
            var tu_ngayParameter = tu_ngay.HasValue ?
                new ObjectParameter("tu_ngay", tu_ngay) :
                new ObjectParameter("tu_ngay", typeof(System.DateTime));
    
            var den_ngayParameter = den_ngay.HasValue ?
                new ObjectParameter("den_ngay", den_ngay) :
                new ObjectParameter("den_ngay", typeof(System.DateTime));
    
            var nhom_theoParameter = nhom_theo != null ?
                new ObjectParameter("nhom_theo", nhom_theo) :
                new ObjectParameter("nhom_theo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoDoanhThuTheoThoiGian_Result>("sp_BaoCaoDoanhThuTheoThoiGian", tu_ngayParameter, den_ngayParameter, nhom_theoParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_HoanTatKiemKe_Result> sp_HoanTatKiemKe(Nullable<int> ma_phieu_kiem_ke)
        {
            var ma_phieu_kiem_keParameter = ma_phieu_kiem_ke.HasValue ?
                new ObjectParameter("ma_phieu_kiem_ke", ma_phieu_kiem_ke) :
                new ObjectParameter("ma_phieu_kiem_ke", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HoanTatKiemKe_Result>("sp_HoanTatKiemKe", ma_phieu_kiem_keParameter);
        }
    
        public virtual ObjectResult<sp_HoanTatNhapKho_Result> sp_HoanTatNhapKho(Nullable<int> ma_phieu_nhap)
        {
            var ma_phieu_nhapParameter = ma_phieu_nhap.HasValue ?
                new ObjectParameter("ma_phieu_nhap", ma_phieu_nhap) :
                new ObjectParameter("ma_phieu_nhap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HoanTatNhapKho_Result>("sp_HoanTatNhapKho", ma_phieu_nhapParameter);
        }
    
        public virtual int sp_HuyDonHang(Nullable<int> ma_don_hang, string ly_do_huy)
        {
            var ma_don_hangParameter = ma_don_hang.HasValue ?
                new ObjectParameter("ma_don_hang", ma_don_hang) :
                new ObjectParameter("ma_don_hang", typeof(int));
    
            var ly_do_huyParameter = ly_do_huy != null ?
                new ObjectParameter("ly_do_huy", ly_do_huy) :
                new ObjectParameter("ly_do_huy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyDonHang", ma_don_hangParameter, ly_do_huyParameter);
        }
    
        public virtual ObjectResult<sp_QuetSkuNhapKho_Result> sp_QuetSkuNhapKho(string ma_vach_hoac_sku, Nullable<int> so_luong_them, Nullable<int> ma_khu_vuc)
        {
            var ma_vach_hoac_skuParameter = ma_vach_hoac_sku != null ?
                new ObjectParameter("ma_vach_hoac_sku", ma_vach_hoac_sku) :
                new ObjectParameter("ma_vach_hoac_sku", typeof(string));
    
            var so_luong_themParameter = so_luong_them.HasValue ?
                new ObjectParameter("so_luong_them", so_luong_them) :
                new ObjectParameter("so_luong_them", typeof(int));
    
            var ma_khu_vucParameter = ma_khu_vuc.HasValue ?
                new ObjectParameter("ma_khu_vuc", ma_khu_vuc) :
                new ObjectParameter("ma_khu_vuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_QuetSkuNhapKho_Result>("sp_QuetSkuNhapKho", ma_vach_hoac_skuParameter, so_luong_themParameter, ma_khu_vucParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_TaoDonHang(string ma_code_don_hang, Nullable<int> ma_nhan_vien, Nullable<int> ma_khach_hang, Nullable<int> ma_khuyen_mai, Nullable<decimal> tien_giam_gia, Nullable<decimal> phi_van_chuyen, string ghi_chu)
        {
            var ma_code_don_hangParameter = ma_code_don_hang != null ?
                new ObjectParameter("ma_code_don_hang", ma_code_don_hang) :
                new ObjectParameter("ma_code_don_hang", typeof(string));
    
            var ma_nhan_vienParameter = ma_nhan_vien.HasValue ?
                new ObjectParameter("ma_nhan_vien", ma_nhan_vien) :
                new ObjectParameter("ma_nhan_vien", typeof(int));
    
            var ma_khach_hangParameter = ma_khach_hang.HasValue ?
                new ObjectParameter("ma_khach_hang", ma_khach_hang) :
                new ObjectParameter("ma_khach_hang", typeof(int));
    
            var ma_khuyen_maiParameter = ma_khuyen_mai.HasValue ?
                new ObjectParameter("ma_khuyen_mai", ma_khuyen_mai) :
                new ObjectParameter("ma_khuyen_mai", typeof(int));
    
            var tien_giam_giaParameter = tien_giam_gia.HasValue ?
                new ObjectParameter("tien_giam_gia", tien_giam_gia) :
                new ObjectParameter("tien_giam_gia", typeof(decimal));
    
            var phi_van_chuyenParameter = phi_van_chuyen.HasValue ?
                new ObjectParameter("phi_van_chuyen", phi_van_chuyen) :
                new ObjectParameter("phi_van_chuyen", typeof(decimal));
    
            var ghi_chuParameter = ghi_chu != null ?
                new ObjectParameter("ghi_chu", ghi_chu) :
                new ObjectParameter("ghi_chu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoDonHang", ma_code_don_hangParameter, ma_nhan_vienParameter, ma_khach_hangParameter, ma_khuyen_maiParameter, tien_giam_giaParameter, phi_van_chuyenParameter, ghi_chuParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
