//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public don_hang()
        {
            this.chi_tiet_don_hang = new HashSet<chi_tiet_don_hang>();
        }
    
        public int ma_don_hang { get; set; }
        public string ma_code_don_hang { get; set; }
        public Nullable<int> ma_khach_hang { get; set; }
        public Nullable<int> ma_nhan_vien { get; set; }
        public Nullable<int> ma_khuyen_mai { get; set; }
        public Nullable<System.DateTime> ngay_dat_hang { get; set; }
        public string trang_thai { get; set; }
        public string trang_thai_thanh_toan { get; set; }
        public decimal tong_tien_hang { get; set; }
        public decimal tien_giam_gia { get; set; }
        public decimal phi_van_chuyen { get; set; }
        public decimal thanh_tien { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<System.DateTime> ngay_huy { get; set; }
        public string ly_do_huy { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual khach_hang khach_hang { get; set; }
        public virtual khuyen_mai khuyen_mai { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
