//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khu_vuc_kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khu_vuc_kho()
        {
            this.phieu_kiem_ke = new HashSet<phieu_kiem_ke>();
            this.san_pham_sku = new HashSet<san_pham_sku>();
        }
    
        public int ma_khu_vuc { get; set; }
        public string ten_khu_vuc { get; set; }
        public string loai_khu_vuc { get; set; }
        public Nullable<decimal> dien_tich_m2 { get; set; }
        public Nullable<bool> trang_thai_hoat_dong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_kiem_ke> phieu_kiem_ke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham_sku> san_pham_sku { get; set; }
    }
}
