//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khuyen_mai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khuyen_mai()
        {
            this.don_hang = new HashSet<don_hang>();
        }
    
        public int ma_khuyen_mai { get; set; }
        public string ma_code_khuyen_mai { get; set; }
        public string ten_khuyen_mai { get; set; }
        public string loai_giam_gia { get; set; }
        public decimal gia_tri_giam { get; set; }
        public Nullable<decimal> gia_tri_don_toi_thieu { get; set; }
        public System.DateTime ngay_bat_dau { get; set; }
        public System.DateTime ngay_ket_thuc { get; set; }
        public Nullable<bool> trang_thai_hoat_dong { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don_hang> don_hang { get; set; }
    }
}
