//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mau_san_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mau_san_pham()
        {
            this.san_pham_sku = new HashSet<san_pham_sku>();
        }
    
        public int ma_mau_san_pham { get; set; }
        public int ma_danh_muc { get; set; }
        public string ten_san_pham { get; set; }
        public string ma_code_ten_sp { get; set; }
        public string mo_ta { get; set; }
        public string duong_dan_hinh_anh { get; set; }
        public Nullable<decimal> gia_thi_truong { get; set; }
        public Nullable<bool> trang_thai_hoat_dong { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        public virtual danh_muc danh_muc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham_sku> san_pham_sku { get; set; }
    }
}
