//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_dung()
        {
            this.bao_cao = new HashSet<bao_cao>();
            this.don_hang = new HashSet<don_hang>();
            this.phieu_kiem_ke = new HashSet<phieu_kiem_ke>();
            this.phieu_nhap_kho = new HashSet<phieu_nhap_kho>();
            this.chuyen_giao_hang = new HashSet<chuyen_giao_hang>();
        }
    
        public int ma_nguoi_dung { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau_ma_hoa { get; set; }
        public string ho_ten { get; set; }
        public string vai_tro { get; set; }
        public Nullable<bool> trang_thai_hoat_dong { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
        public string email { get; set; }
        public string so_dien_thoai { get; set; }
        public string dia_chi { get; set; }
        public Nullable<int> ma_tinh_thanh { get; set; }
        public Nullable<int> ma_quan_huyen { get; set; }
        public Nullable<int> ma_phuong_xa { get; set; }
        public string dia_chi_chi_tiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bao_cao> bao_cao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don_hang> don_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_kiem_ke> phieu_kiem_ke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_nhap_kho> phieu_nhap_kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chuyen_giao_hang> chuyen_giao_hang { get; set; }
    }
}
