//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nha_cung_cap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nha_cung_cap()
        {
            this.phieu_nhap_kho = new HashSet<phieu_nhap_kho>();
        }
    
        public int ma_nha_cung_cap { get; set; }
        public string ma_code_ncc { get; set; }
        public string ten_nha_cung_cap { get; set; }
        public string so_dien_thoai { get; set; }
        public string dia_chi { get; set; }
        public Nullable<bool> trang_thai_hoat_dong { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_nhap_kho> phieu_nhap_kho { get; set; }
    }
}
