//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieu_nhap_kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieu_nhap_kho()
        {
            this.chi_tiet_phieu_nhap_kho = new HashSet<chi_tiet_phieu_nhap_kho>();
        }
    
        public int ma_phieu_nhap { get; set; }
        public string ma_code_phieu_nhap { get; set; }
        public Nullable<int> ma_nha_cung_cap { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public Nullable<System.DateTime> ngay_nhap { get; set; }
        public string trang_thai { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<decimal> tong_tien_hang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_phieu_nhap_kho> chi_tiet_phieu_nhap_kho { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual nha_cung_cap nha_cung_cap { get; set; }
    }
}
