//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieu_kiem_ke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieu_kiem_ke()
        {
            this.chi_tiet_kiem_ke = new HashSet<chi_tiet_kiem_ke>();
        }
    
        public int ma_phieu_kiem_ke { get; set; }
        public string ma_code_kiem_ke { get; set; }
        public System.DateTime ngay_kiem_ke { get; set; }
        public Nullable<int> ma_khu_vuc { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public string trang_thai { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_kiem_ke> chi_tiet_kiem_ke { get; set; }
        public virtual khu_vuc_kho khu_vuc_kho { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
