//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham_sku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public san_pham_sku()
        {
            this.chi_tiet_don_hang = new HashSet<chi_tiet_don_hang>();
            this.chi_tiet_kiem_ke = new HashSet<chi_tiet_kiem_ke>();
            this.chi_tiet_phieu_nhap_kho = new HashSet<chi_tiet_phieu_nhap_kho>();
            this.thuoc_tinh = new HashSet<thuoc_tinh>();
        }
    
        public int ma_sku { get; set; }
        public string ma_code_sku { get; set; }
        public int ma_mau_san_pham { get; set; }
        public int ma_lo_hang { get; set; }
        public int so_thu_tu { get; set; }
        public string tom_tat_thuoc_tinh { get; set; }
        public string ma_vach { get; set; }
        public decimal gia_von { get; set; }
        public decimal gia_niem_yet { get; set; }
        public int so_luong { get; set; }
        public string trang_thai_vong_doi { get; set; }
        public Nullable<int> ma_khu_vuc { get; set; }
        public string ma_vi_tri { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_kiem_ke> chi_tiet_kiem_ke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_phieu_nhap_kho> chi_tiet_phieu_nhap_kho { get; set; }
        public virtual khu_vuc_kho khu_vuc_kho { get; set; }
        public virtual lo_hang lo_hang { get; set; }
        public virtual mau_san_pham mau_san_pham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thuoc_tinh> thuoc_tinh { get; set; }
    }
}
