//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thuoc_tinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thuoc_tinh()
        {
            this.san_pham_sku = new HashSet<san_pham_sku>();
        }
    
        public int ma_thuoc_tinh { get; set; }
        public string loai_thuoc_tinh { get; set; }
        public string ten_thuoc_tinh { get; set; }
        public string ma_code_thuoc_tinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham_sku> san_pham_sku { get; set; }
    }
}
